pool : MYAGENT
trigger: 
 branches:
   include:
     - main

pr:
  branches:
    include:
      - main

variables:
  workingdirectory: $(System.DefaultWorkingDirectory)   
  serviceconnection: MYSERVICE

stages:
  - stage: validation
    displayName: VALIDATION-STAGE   
    jobs:
      - job: validationjob
        displayName: VALIDATIONJOB
        steps:
        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'MYSERVICE'
            backendAzureRmStorageAccountName: 'tfstate098'
            backendAzureRmContainerName: 'tfstate098container'
            backendAzureRmKey: 'terraform1.tfstate'


  - stage: apply
    displayName: APPLY-STAGE
    jobs:
      - job: apply
        displayName: APPLY-JOB
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'MYSERVICE'
            backendAzureRmStorageAccountName: 'tfstate098'
            backendAzureRmContainerName: 'tfstate098container'
            backendAzureRmKey: 'terraform1.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'MYSERVICE'


        
         

          