pool : 
 name: MYAGENT

variables:

stages:
  - stage: validatestage
    displayName: VALIDATE STAGE
    jobs:
      - job: validatejob
        displayName: VALIDATE-JOB
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'MY-SERVICE'
            backendAzureRmStorageAccountName: 'rewalsar'
            backendAzureRmContainerName: 'koot'
            backendAzureRmKey: 'terraform1.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage: plan-stage 
    displayName: PLAN-STAGE
    jobs:
      - job: plan-job
        displayName: PLAN-JOB 
        steps:

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'MY-SERVICE'
            backendAzureRmStorageAccountName: 'rewalsar'
            backendAzureRmContainerName: 'koot'
            backendAzureRmKey: 'terraform1.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'MY-SERVICE'

  - stage: manual=approval
    jobs:
      - job: manual-approval
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'abc@rakutem.com'

  - stage: terraform-apply 
    displayName: APPLY-STAGE
    dependsOn: manual=approval
    condition: succeeded()
    jobs:
      - job: applyjob
        displayName: APPLY-JOB 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'MY-SERVICE'
            backendAzureRmStorageAccountName: 'rewalsar'
            backendAzureRmContainerName: 'koot'
            backendAzureRmKey: 'terraform1.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'MY-SERVICE'
               
        
